name: Update Map with Cleaned Data

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main

jobs:
  update-map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas folium

      - name: Run the clean data script
        run: |
          python Clean\ data.py

      - name: Commit updated map
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add venlo_map.html
          git commit -m "Updated map with latest data"
          git push
